# Generated by Django 4.0 on 2022-01-02 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.ManyToManyField(to='routine.Author')),
            ],
        ),
        migrations.CreateModel(
            name='BookProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('start_page', models.IntegerField()),
                ('end_page', models.IntegerField()),
                ('is_done', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.book')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JustDoIt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep', models.IntegerField()),
                ('weight', models.IntegerField(blank=True, help_text='Weight in kilograms', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=25)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudyChunkScoreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=25, unique=True)),
                ('goal', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('start_page', models.IntegerField()),
                ('end_page', models.IntegerField()),
                ('authors', models.ManyToManyField(blank=True, to='routine.Author')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('exercise', models.ManyToManyField(to='routine.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='StudyChunkScoreCardPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('achieved', models.IntegerField()),
                ('target', models.IntegerField()),
                ('did_today', models.BooleanField(default=False)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.studychunkscorecard')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('item', models.ManyToManyField(to='routine.RoutineItem')),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('item', models.ManyToManyField(to='routine.RoutineItemOrder')),
            ],
        ),
        migrations.CreateModel(
            name='ReadChunkScoreCardPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('achieved', models.IntegerField()),
                ('target', models.IntegerField()),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.bookprogress')),
            ],
        ),
        migrations.CreateModel(
            name='JustDoItDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('justdoit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.justdoit')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='reps',
            field=models.ManyToManyField(to='routine.Reps'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='type_of_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.typeofexercise'),
        ),
        migrations.CreateModel(
            name='BooksReadThisYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2022)),
                ('goal', models.IntegerField(help_text='How many books I plan to read')),
                ('books', models.ManyToManyField(blank=True, to='routine.BookProgress')),
            ],
        ),
    ]
